# Generated by Django 4.2.2 on 2023-06-08 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('born', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('teamid', models.IntegerField()),
                ('photo', models.ImageField(upload_to='player_photos/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='team_photos/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edpi', models.FloatField()),
                ('dpi', models.IntegerField()),
                ('polling_rate', models.IntegerField()),
                ('sensitivity', models.FloatField()),
                ('yaw', models.FloatField()),
                ('zoom', models.FloatField()),
                ('raw_input', models.BooleanField()),
                ('mouse', models.CharField(max_length=50)),
                ('mousepad', models.CharField(max_length=50)),
                ('monitor', models.CharField(max_length=50)),
                ('refresh_rate', models.IntegerField()),
                ('in_game_resolution', models.CharField(max_length=50)),
                ('scaling', models.CharField(max_length=50)),
                ('keyboard', models.CharField(max_length=50)),
                ('headset', models.CharField(max_length=50)),
                ('sharecode', models.CharField(max_length=50)),
                ('commands', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
            ],
        ),
    ]
